freebsd11_task:
        freebsd_instance:
                image: freebsd-11-2-release-amd64
        install_script:
                - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
                - pkg upgrade -y
                - pkg install -y autoconf automake libtool pkconfig meson ninja gtk3
        autoconf_script:
                - autoreconf -i
                - ./configure --with-hello --with-gtk
                - make 
        meson_script: 
                - meson -Dhello=true -Dgoodbye=false -Dgtk=true _build
                - ninja -C _build

freebsd12_task:
        freebsd_instance:
                image: freebsd-12-0-release-amd64
        install_script:
                - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
                - pkg upgrade -y
                - pkg install -y autoconf automake libtool pkconfig meson ninja gtk3
        autoconf_script:
                - autoreconf -i
                - ./configure --with-hello --with-gtk
                - make 
        meson_script: 
                - meson -Dhello=true -Dgoodbye=false -Dgtk=true _build
                - ninja -C _build
